spring.application.name=calendar-mcp
server.port=9494



spring.ai.mcp.server.type=sync
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=calendar-mcp
spring.ai.mcp.server.version=1.0.0

spring.main.web-application-type=none
spring.main.banner-mode=off
logging.pattern.console=

